CREATE TABLE bbs.users (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    login_id VARCHAR(255) NOT NULL BINARY UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    
);

ALTER TABLE users CHANGE COLUMN login_id login_id VARCHAR(255)　UNIQUE
ALTER TABLE users CHANGE COLUMN password password  VARCHAR(255) NOT NULL binary;